version: 2

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: dc5114f2dbc5335725be25c9fe4cf7d915085910dea37581b1fc92176ffdf2b1
    docker:
      - image: circleci/php:7.2-cli-node-browsers

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y libzip-dev
            sudo docker-php-ext-install zip pcntl
            wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer
      - run:
          name: Set up Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Install Composer dependencies
          command: |
            sudo composer self-update
            composer install -n --prefer-dist
            composer dump-autoload --optimize
      - run:
          name: Run syntax tests
          command: php php-cs-fixer fix --dry-run
      - run:
          name: Run unit tests
          command: |
            sudo docker-php-ext-enable xdebug
            ./cc-test-reporter before-build
            php bin/phpunit --stop-on-error --stop-on-failure -v --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

      - run:
          name: Clone E2E tests
          command: git clone https://github.com/contentful/the-example-app-e2e-tests.git ./tests-e2e
      - run:
          name: Install E2E tests dependencies
          command: |
            cd tests-e2e
            npm install
      - run:
          name: Run E2E tests
          command: |
            php bin/console --env=dev server:start 127.0.0.1:8000
            php bin/console --env=staging cache:warmup
            echo "APP_ENV=staging" > .env
            ./tests-e2e/node_modules/.bin/cypress run
